#include(pwlib/pwlib.hlsl)
#includeinfolder(damionshard/dsaascripts)

[game]
jumptoscript("setup");

[setup]
runscript("pw_initpwlib");
runscript("pw_initpwbgs");
loadtexture(12112,"damionshard/dsnameboxes.png");
loadtexture(61017,"damionshard/objection_purple.png");
changetitle("Voices Test (Spoilers!)");
jumptoscript("run");

[run]
runscript("pw_createphoenix");
runscript("pw_creategodot");
runscript("pw_createkarma");
runscript("pw_createjudge");
runscript("showpwchar");
runscript("pw_showadvarrowmenu");
runscript("pw_showmessagebox");
runscript("pw_showattorneystand");
runscript("pw_enablephoenixnormal");
runscript("setlipsynctochar");
runscript("pw_setnameboxtodamion");
message("This is a test script for \nYggdrasilsSword's Voice\nOver Lines.");

runscript("pw_showprosecutorstand");
runscript("pw_enablegodotnormal");
runscript("pw_setnameboxtogregor");
loadandplaysfx("../voices/01 - DV.wav",0);
runscript("pw_disableticking");
messageauto("It is useless to resist!");
wait(45);
messageappend("\nDon't let yourself be destroyed\nas Meson did!");
runscript("pw_hidemessagebox");
loadandplaysfx("../voices/02 - DV.wav",0);
wait(75);
runscript("pw_setnameboxtogregor");
runscript("pw_disableticking");
runscript("pw_showmessagebox");
messageauto("There is no escape.");
wait(75);
messageappend("\nDon't make me destroy you.");
loadandplaysfx("../voices/03 - DV.wav",0);
messageauto("Damion,");
wait(60);
messageappend(" you do not yet\nrealize your importance.");
loadandplaysfx("../voices/04 - DV.wav",0);
message("You have only begun to\ndiscover your power.");
loadandplaysfx("../voices/05 - DV.wav",0);
messageauto("Join me,");
wait(70);
messageappend(" and I will\ncomplete your training.");
loadandplaysfx("../voices/06 - DV.wav",0);
messageauto("With our combined strength,");
wait(50);
messageappendauto(" we\ncan end this destructive conflict,");
wait(65);
messageappend("\nand bring order to the courtroom.");
runscript("pw_showattorneystand");
runscript("pw_enablephoenixnormal");
runscript("pw_setnameboxtodamion");
runscript("pw_disableticking");
loadandplaysfx("../voices/07 - Luke.wav",0);
message("I'll never join you!");
runscript("pw_showprosecutorstand");
runscript("pw_enablegodotnormal");
runscript("pw_setnameboxtogregor");
runscript("pw_disableticking");
loadandplaysfx("../voices/08 - DV.wav",0);
messageauto("If you only knew the power");
wait(60);
messageappend("\nof the dark side.");
loadandplaysfx("../voices/09 - DV.wav",0);
messageauto("Lord Shard never told you");
wait(45);
messageappend("\nwhat happened to your father.");
runscript("pw_showattorneystand");
runscript("pw_enablephoenixnormal");
runscript("pw_setnameboxtodamion");
runscript("pw_disableticking");
loadandplaysfx("../voices/10 - Luke.wav",0);
message("He told me enough!");
loadandplaysfx("../voices/11 - Luke.wav",0);
message("He told me you killed him!");
runscript("pw_showprosecutorstand");
runscript("pw_enablegodotnormal");
runscript("pw_setnameboxtogregor");
runscript("pw_disableticking");
loadandplaysfx("../voices/12 - I Am Your Father.wav",0);
messageauto("No.");
wait(60);
messageappendauto(" I");
wait(45);
messageappendauto(" am your father.");
wait(270);
setvar([sld_targetcharanim],"pw_enablephoenixnormal");
runscript("pw_slideprosecutortoattoney");
runscript("pw_hidemessagebox");
wait(20);
runscript("pw_showmessagebox");
runscript("pw_setnameboxtodamion");
runscript("pw_disableticking");
messageauto("No!");
wait(90);
messageappendauto(" No!");
wait(90);
messageauto("That's not true!");
wait(120);
runscript("pw_enablephoenixohshit");
messageappend("\nThat's impossible!");
runscript("pw_showprosecutorstand");
runscript("pw_enablegodotnormal");
runscript("setlipsynctochar");
runscript("pw_setnameboxtogregor");
runscript("pw_disableticking");
loadandplaysfx("../voices/13 - Search Your Feelings.wav",0);
messageauto("Search your feelings.");
wait(30);
messageappend("\nYou know it to be true.");
runscript("pw_showattorneystand");
runscript("pw_enablephoenixemo");
runscript("pw_setnameboxtodamion");
runscript("pw_disableticking");
loadandplaysfx("../voices/14 - Luke.wav",0);
messageauto("Noooooooooooooooooo!");
wait(90);
messageappend("\nNooooooo!");
runscript("pw_hidemessagebox");
runscript("pw_showprosecutorstand");
runscript("pw_enablegodotnormal");
runscript("setlipsynctochar");
loadandplaysfx("../voices/15 - DV.wav",0);
wait(30);
runscript("pw_setnameboxtogregor");
runscript("pw_disableticking");
runscript("pw_showmessagebox");
messageauto("Damion,");
wait(30);
messageappendauto(" you can destroy Lord\nShard.");
wait(60);
messageappend(" He has forseen this.");
loadandplaysfx("../voices/16 - DV.wav",0);
runscript("pw_hidemessagebox");
wait(15);
runscript("pw_showmessagebox");
message("It is your destiny.");
loadandplaysfx("../voices/17 - DV.wav",0);
messageauto("Join me,");
wait(60);
messageappendauto(" and together");
wait(30);
messageappend(" we\ncan rule the courtroom\nas father and son.");
loadandplaysfx("../voices/18 - DV.wav",0);
messageauto("Come with me.");
wait(60);
messageappend(" It is\nthe only way.");
runscript("pw_raiseobjectionshard");
setvar([sld_targetcharanim],"pw_enablekarmafrontnormal");
runscript("pw_slideprosecutortowitness");
runscript("pw_setnameboxtoshard");
message("That's enough!");
message("Your Honor, I demand that you\nhand down a verdict immediately!");
message("My attorney has clearly already\nproven my innocence beyond doubt.");
message("As touching as I find this...\nfamily reunion.");
quit();